### ISSUE TITLE
Hover contrast not passing minimum contrast

### ISSUE THREAD

**Issue by GGD4V** [MeD-DMC/adapt-esdc-college-theme#32]
Issue: After launching "View Valuing Individuality" and going back to the root page, the button has a gay background, which passes the minimum contrast ration until you hover the button with your mouse (the gray become more pale). How to fix: It's alright to have a change of colour on hover, as long as the hover colour is still dark enough to pass contrast ratio. Shift the hover colour down to at least #676767.

**Comment by falcochip** [comment]
hover color is currently darker - #1a1a1a. 
seems fixed
