### ISSUE TITLE
Component - Hotgrid - Item Title color

### ISSUE THREAD

**Issue by bryan-franey** [MeD-DMC/adapt-esdc-college-theme#45]
The Hotgrid component renders trigger images as button tags, formatted as `<button class="base hotgrid-grid-item hotgrid-item-states-css " data-index="0">...</button>`.  Text can be added below the image in the button using the **Item Title** field in the Hotgrid item editor.  The two style rules described below result in the Item Title text being rendered as white text over a white background.  Please see the screenshot below for an example.

1. [Line 7 in less/core/buttons.less](https://github.com/MeD-DMC/adapt-esdc-college-theme/blob/ef27831711d9d235da2be0f4b6046926d2f30221/less/core/buttons.less#L7) specifies that button element text color is white.
2. [Line 25 is the same file](https://github.com/MeD-DMC/adapt-esdc-college-theme/blob/ef27831711d9d235da2be0f4b6046926d2f30221/less/core/buttons.less#L25) specifies that buttons with the class `base` will have a transparent background.  Hotgrid buttons are rendered in component regions with a white background, which means that the white button text will not be visible.

There is currently only one rule in the theme pertaining to this plugin ([line 766 in less/custom/theme-extras.less](https://github.com/MeD-DMC/adapt-esdc-college-theme/blob/ef27831711d9d235da2be0f4b6046926d2f30221/less/custom/theme-extras.less#L766)).  Suggest creating the overrides listed below in a new file: `less/plugins/adapt-contrib-hotgrid/hotgrid.less`.

- `button.hotgrid-grid-item .hotgrid-item-title` needs a dark text color, such as `color: #333`
- `button.hotgrid-grid-item.visited .hotgrid-item-title`, needs a dark text color to appear over a grey background (`#b2b2b2`), so probably black `color: #000`

![Hotgrid_title_issue](https://user-images.githubusercontent.com/15460788/141377965-409305e4-5273-4c52-97fc-09fd8e041c07.png)

**Comment by falcochip** [comment]
button.hotgrid-grid-item .hotgrid-item-title{
    color: #333;
}

visited style not required as item does not have grey background when visited

**Comment by MeD-Owner** [comment]
> button.hotgrid-grid-item .hotgrid-item-title{ color: #333; }
> 
> visited style not required as item does not have grey background when visited

Hmm I thought they did have a grey background when visited - I believe it's when you don't specify a visited image, then it defaults to a grey but if you put the same image in visited as the normal state then it won't change - to look into, we might have to darken the text on that too.

**Comment by falcochip** [comment]
// Hot grid item title style - issue #45
button.hotgrid-grid-item .hotgrid-item-title{
    color: #333;
    font-weight: 500;
}
.hotgrid-component .visited:after {
    background-color: rgba(172,172,172,0.2);
    button.hotgrid-grid-item .hotgrid-item-title{
        color: #000;
    }
}
