### ISSUE TITLE
Tables - styling

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/adapt-esdc-college-theme#47]
In certain components, tables don't have borders (not grabbing the styles from theme)

**Comment by falcochip** [comment]
table styles were only applied to .text-body classes. Updated line 622 in theme-extras.less
`//Table styles
[class$="-body"] table th, [class$="-body"] table td {
    border:  2px solid @esdc-dark-blue;
    border-spacing: 0;
    padding: 10px;
}
[class$="-body"] table th {
    background-color: @esdc-dark-blue;
    color: @esdc-white;
}`
