### ISSUE TITLE
Resources - various CSS issues

### ISSUE THREAD

**Issue by MeD-Owner** [MeD-DMC/adapt-esdc-college-theme#50]
When adding links to resources, they are now default blue/purple, color should match other types of resources (not sure if we need a visited color? probably not)

![image](https://user-images.githubusercontent.com/18216769/153084827-f0d5fe94-708a-466a-9a0a-04bd5f51cb36.png)

Also in resources, titles are not bolded but descriptions are - maybe we should swap them? to test and see if it looks good.

When resources links color issue fixed and live, let Jeff Scott know

**Comment by falcochip** [comment]
![image](https://user-images.githubusercontent.com/78871138/153269278-80477aa1-1569-4298-9153-f3bc85fca65a.png)

.drawer-item-title-inner {
    font-weight: 700;
    padding: 2px 0;
}
.drawer-item-description-inner{
    font-weight:100;
}
