### ISSUE TITLE
MultiChoice - Pink focus box

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/adapt-esdc-college-theme#55]
Focux box covers all choices instead of the currently focused one

![image](https://user-images.githubusercontent.com/43245289/154996317-7c43c99a-43cd-496f-ba70-1ab7ea1b0ddb.png)

**Comment by falcochip** [comment]
![image](https://user-images.githubusercontent.com/78871138/158174577-0d2a0797-c84a-4fdc-bda5-703a5ca2715d.png)

Added focus to selected radio button - kept to pink as current theme only has one focus color

**Comment by ftourangeau** [comment]
Removed the focus on radio button as it was a color change only (no change in shape).
Added focus outline to individual inputs and removed focus outline from the radiobox div
Also made the outline identical in color and stroke size for everything
![mcq_focus_outline](https://user-images.githubusercontent.com/93537804/195406201-6081e831-c13a-468b-b85d-721089844a9a.jpg)
