### ISSUE TITLE
Blocks - titles

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/adapt-esdc-college-theme#56]
Do block titles pass contrast requirements? To investigate

![Screenshot-2022-02-28_Block_Title_Contrast](https://user-images.githubusercontent.com/43245289/156016007-a8b2d73c-8295-44c5-bd04-e835e093ce5f.png)

**Comment by falcochip** [comment]
Yes, this combination does not pass the color contrast. 
![image](https://user-images.githubusercontent.com/78871138/158450234-727ce148-1b4b-44d5-91e8-0f4e0f3b15a2.png)

Maybe switch to the following combination
![image](https://user-images.githubusercontent.com/78871138/158450893-2c91944f-8385-437b-9582-feed63e4c55f.png)
