### ISSUE TITLE
Overlapping of the "X" icon in Show feedback button

### ISSUE THREAD

**Issue by ftourangeau** [MeD-DMC/adapt-esdc-college-theme#60]
When using "Display marking" on a question, the "X" icon displayed in the "Show feedback" button overlaps the button text on screen with smaller width.
![overlapping](https://user-images.githubusercontent.com/93537804/157915118-b7790f57-ad99-4645-97f6-d238bfcc396c.jpg)

**Comment by falcochip** [comment]
remove following code from theme
`.buttons .buttons-marking-icon {
    left:unset !important;
    right:25px;
}`
